apiVersion: apps/v1
kind: Deployment
metadata:
  name: ashwin-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ashwin-app
  template:
    metadata:
      labels:
        app: ashwin-app
    spec:
      containers:
        - name: ashwin-container
          image: ashwinr2001/may042025projecthotsar:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ashwin-service
spec:
  selector:
    app: ashwin-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30444
  type: NodePort
